### ISSUE TITLE
Lua 5.1 compatability

### ISSUE THREAD

**Issue by bhane** [Tangent128/lua-evdev#3]
Including this in a bare love2d project
```lua
evdev = require("evdev")
```
returns this for me
```lua
error loading module 'evdev.core' from file './evdev/core.so':
	./evdev/core.so: undefined symbol: luaL_setfuncs
```

**Comment by Tangent128** [comment]
Ah, yes. Love2D is frozen at Lua 5.1 I believe, while lua-evdev currently supports 5.2 and 5.3.

There's no special reason it CAN'T support 5.1, it just doesn't yet since there are just some API differences to account for.

Adjusted title to use this issue for tracking 5.1 support.

(though I should ask, does love.joystick provide the features you need?)

**Comment by bhane** [comment]
Thanks for the clarification!
love.joystick has a lot of great features, but I'd like to grab keyboard input from a non-focused window, and love.keyboard doesn't support that.

**Comment by Tangent128** [comment]
OK; brought in lua-compat-5.3 to extend support down to Lua 5.1.

Would you mind trying out the latest master to see if it works?

(keep in mind that the input device you want to use will need to have its permissions set so that your love2d process can open them; for obvious reasons, Linux doesn't default to letting any random process grab the keyboard)

**Comment by bhane** [comment]
The latest master works. With the right permissions I can read keyboard events from love2d. Great work!
